### ISSUE TITLE
Query did not produce intended results

### ISSUE THREAD

**Issue by driskerr** [gilcaz/sql-scratch-capstone-turn-in#4]
https://github.com/gilcaz/sql-scratch-capstone-turn-in/blob/6e9df71c3b2c0b3ac59bbf4336e43f17b6364842/Gilbert%20Cazessus%20Capstone/Gilbert%20Cazessus%20Capstone.sql#L19-L31

Your query as written pulls in the utm_source and utm_campaign for every user interaction. However, we were looking for you to summarize this information to get the *number* of interactions each utm_campaign was responsible for.

To accomplish this, you need to add a `COUNT()` calculation to your column statements and then use `GROUP BY` to summarize by the utm_campaign. 

In the end, we were looking for something like this:
```
  WITH first_touch AS (
	SELECT user_id,
  		MIN(timestamp) AS first_touch_at
  	FROM page_visits
  	GROUP BY user_id)
  SELECT ft.user_id,
  	ft.first_touch_at,
    pv.utm_source,
    	pv.utm_campaign,
      COUNT(utm_campaign)
 FROM first_touch ft
 JOIN page_visits pv
 	ON ft.user_id = pv.user_id
  AND ft.first_touch_at = pv.timestamp
    GROUP BY utm_campaign
  ORDER BY 5 DESC;
```

**Comment by gilcaz** [comment]
I'm sorry, I must have mislabel the query for issue # 4.  The query you're requestin in the las query and also on the presentation page 9.
